[build]
  command = "npm run build"
  publish = ".svelte-kit/output/static"
  functions = ".svelte-kit/output/server"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10.2.4"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sveltejs/kit"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = ".svelte-kit/output/static"
  autoLaunch = false
