[build]
  command = "npm run build"
  publish = ".svelte-kit/output/static"
  functions = ".svelte-kit/output/server"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.6.0"

[dev]
  framework = "#custom"
  command = "vite dev"
  targetPort = 5173
  port = 8888
  publish = ".svelte-kit/output/static"
  autoLaunch = false
